---
title: "report_health"
author: "Luke Barker"
date: "23/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)    # includes readr & tibble
library(lubridate)    # for dates
library(stringr)      # useful string library
library(scales)       # scale control

# base theme settings here:
theme_set(theme_bw())

## adjust columns to be more manageable:
corrected_cols <- cols(
  Entity = col_character(),
  Code = col_character(),
  Year = col_integer()
)

# import two datasets
dbvhe  <- readr::read_csv("data/disease-burden-vs-health-expenditure-per-capita.csv", col_types=corrected_cols) 

ndbrf  <- readr::read_csv("data/number-of-deaths-by-risk-factor.csv", col_types=corrected_cols)

# remove cumbersome column names prefix, then the suffix
ndbrf <- ndbrf %>% 
  
  rename_with(stringr::str_replace, pattern='Deaths - Cause: All causes - Risk: ', replacement="") %>%
  rename_with(gsub, pattern=" - .*", replacement="")



```
```{r causes-death}
causes_totals <- ndbrf %>%
  # we are adding all years and treating it as globally (add all countries only)
  # filter so just the countries, i.e. ones with ISO code 
  filter(!is.na(Code)) %>%
  summarise(across(c(4:31) , sum)) %>%
  pivot_longer(c(1:28), values_to="total") %>%
  arrange(desc(total))


print(causes_totals)

  
# TODO:make this a kable table
head(causes_totals, 5)

# demonstrate better via a column plot of all deaths 
## fix scales of big numbers
p <- ggplot(data=causes_totals, aes(x = reorder(name, -total), y=total )) +
  geom_col(fill="steelblue") + 
  coord_flip()  +
  scale_y_continuous(labels=scales::comma, expand = c(0,0)) +
  labs(x="Death\'s risk factor", y="Estimated total value", title="Estimated totals for deaths attributable to risk factor, globally, 1990-2019") +
  theme(plot.title = element_text(face = "bold",
                                  hjust=0.5,
                                  color="#555555"),
        plot.title.position = "plot",
        axis.title.x= element_text(color="#775555"),
        axis.title.y= element_text(color="#775555")
        )
  


```

```{r causes-trends}

# multi line graph? 
# https://stackoverflow.com/questions/53125393/ggplot-label-the-top-n-lines

causes_trends <- ndbrf %>% 
  filter(!is.na(Code)) %>%
  group_by(Year) %>% 
  summarise(across(c(3:30), sum)) %>%
  pivot_longer(c(2: 29), values_to="total") %>%
  ggplot(aes(x=Year, y=total)) +
  facet_wrap(~ name, ncol=4) +
  geom_area(colour="orange", fill="orange", 
            show.legend=FALSE) +
  scale_y_continuous(labels=scales::label_number(unit = "M", scale = 1e-6, accuracy=1)) +
  labs(title="Global trends: deaths attributable to risk factors 1990-2020", 
    y="No. Deaths attributable to risk factor (millions)")

# output plot, make grid look better, and hack the facet grid font label size & grid spacing 
causes_trends + theme(
  strip.text.x=element_text(size=10), 
  panel.margin=unit(.5, "lines"),
  axis.text.y=element_text(size=9)
  )
# TODO:make this a kable table
head(causes_trends, 2)


```

```{r smoking-alcohol}

```

```{r expenditures}

```

```{r subjective}

```

```{r conclusions}

```





